site_name: Cours - Florent Fougères
site_url: https://florentfougeres.github.io/cours/
repo_name: "cours"
repo_url: "https://github.com/florentfougeres/cours"

theme:
  name: material
  extra_css:
    - assets/stylesheets/extra.css
  palette:
    # Palette clair
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre

    # Palette sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair

  features:
    - navigation.hide
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - content.code.copy
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - md_in_html
plugins:
  - search:
      lang: fr
  - mermaid2
nav:
  - Accueil: index.md
  - DuckDB:
    - Présentation: duckdb/presentation.md
    - Exercice: duckdb/exercice.md
use_directory_urls: false